YourBookStore.PL/Controllers/UsersController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using YourBookStore.BLL.Interfaces;
using YourBookStore.BLL.Validations;
using YourBookStore.Domain.DTOs;
using YourBookStore.Domain.ViewModels;
using YourBookStore.Utility.GlobalConstants;

namespace YourBookStore.PL.Controllers;

public class UsersController : Controller
{
    private readonly IMapper _mapper;

    private readonly IUserService _userService;
    private readonly IOrderService _orderService;
    private readonly IBookService _bookService;

    public UsersController(IUserService userService, IBookService bookService, IMapper mapper, IOrderService orderService)
    {
        _userService = userService;
        _orderService = orderService;
        _bookService = bookService;
        _mapper = mapper;
    }
    
    [HttpGet("SignIn")]
    [AllowAnonymous]
    public ActionResult SignIn()
    {
        return View("SignIn", new LoginViewModel());
    }

    [HttpPost("SignIn")]
    [AllowAnonymous]
    public async Task<ActionResult> SignIn(LoginViewModel login)
    {
        if (!ModelState.IsValid)
        {
            return View("SignIn");
        };
        
        try
        {
            await _userService.SignInAsync(_mapper.Map<UserDTO>(login), HttpContext);
            return Redirect("/Home");
        }
        catch (YourBookStoreException e)
        {
            ModelState.AddModelError(nameof(LoginViewModel.Email), "Неправильний логін або пароль");
        
        }
        
        return View("SignIn", login);

    }
    
    [HttpGet("SignOut")]
    public async Task<ActionResult> SignOut()
    {
        await _userService.SignOutAsync(HttpContext);
        return Redirect("/Home");
    }
    
    [HttpGet("SignUp")]
    [AllowAnonymous]
    public ActionResult SignUp()
    {
        return View("SignUp");
    }

    [HttpPost("SignUp")]
    [AllowAnonymous]
    public async Task<ActionResult> SignUp(RegistrationViewModel model)
    {
        if (_userService.IsUserExists(model.Email))
        {
            ModelState.AddModelError("Email", "Користувач з цим Email вже існує");
        }

        if (!ModelState.IsValid)
        {
            return View("SignUp", model);
        }

        await _userService.CreateAsync(_mapper.Map<UserDTO>(model));
        await SignIn(new LoginViewModel
        {
            Email = model.Email,
            Password = model.Password
        });
        return Redirect("/Home");
    }
    
    [HttpGet("Profile")]
    [Authorize]
    public ActionResult Profile()
    {
        if (HttpContext.User.Identity.IsAuthenticated)
        {
            var email = User.Claims.FirstOrDefault(x=>x.Type == "Name")?.Value;
            var user = _userService.GetUserByEmail(email);
            if (user is null) Redirect("SignIn");
            var userMapped = _mapper.Map<UserViewModel>(user);
            var userOrders = _orderService.GetOrdersByUserName(userMapped.Email).ToList();
            List<BookDTO> orderedBooks = new List<BookDTO>();
            foreach (OrderDTO order in userOrders)
            {
                foreach(OrderDetailsDTO orderDetail in order.OrderDetails)
                {
                    var book = _bookService.GetBookByIdAsync(orderDetail.BookId).Result;
                    orderDetail.Book = book;
                }
            }

            ViewBag.Books = orderedBooks;

            if (userOrders != null || userOrders.ToList().Count != 0)
            {
                ViewBag.Orders = userOrders; 
            }
            else
            {
                ViewBag.Orders = new List<OrderDTO>();
            }

            return View("UserProfile", userMapped);
        }
        
        return Redirect("SignIn");;
    }

    [HttpGet("Profile/Edit")]
    [Authorize]
    public ActionResult EditProfile(string email)
    {
        var user = _userService.GetUserByEmail(email);
        var userMapped = _mapper.Map<UserViewModel>(user);
        return View("UserProfileEdit", userMapped);
    }

    [HttpPost("Profile/Edit")]
    [Authorize]
    public async Task<ActionResult> EditProfile(UserViewModel model)
    {
        if (!ModelState.IsValid)
        {
            return View("UserProfileEdit", model);
        }
        var userMapped = _mapper.Map<UserDTO>(model);
        await _userService.UpdateUserAsync(userMapped);
        return Redirect("/Profile");
    }


}

YourBookStore.PL/Views/Users/SignIn.cshtml
@model YourBookStore.Domain.ViewModels.LoginViewModel
@{
    Layout = null;
 }
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="../css/style.css">
	<title>Document</title>
</head>

<body class="body_white">
	<div class="wrapper">
		<main class="main">
			<!--RENDER BODY-->
			<div class="row-container">
				<div class="left-container">
					<img src="../src/img/ui/library.svg" alt="" class="left-container__image">
				</div>
				<div class="right-container">
					<div class="right-container__content">
						<a asp-controller="Home" asp-action="Index" class="right-container__logo"><img src="../src/img/ui/logo.svg" alt=""></a>
						<form asp-area="" asp-controller="Users" asp-action="SignIn" method="post" class="sign-in-form">
						
							<div class="input-item">
								<label class="input-item__label" asp-for="Email"><h5>Email</h5></label>
								@Html.TextBoxFor(m => m.Email, new { placeholder = "Email", type="email", @class = "text-input input-large _input-large-description-font" })
									
							</div>
							<div class="input-item">
								<label class="input-item__label" asp-for="Password"><h5>Пароль</h5></label>
								@Html.TextBoxFor(m => m.Password, new { placeholder="Пароль",  type="password", @class = "text-input input-large _input-large-description-font" })
							</div>
							<span asp-validation-for="Email" class="error-message validation-error _regular-interface-font"></span>
							<span asp-validation-for="Password" class="error-message validation-error _regular-interface-font"></span>
							<input type="submit" class="button-large" value="Увійти">
							<div class="sign-form__redirect _regular-interface-font">
								<span>У вас немає аккаунту? </span>
								<div class="validation" asp-validation-summary="ModelOnly"></div>
								@Html.ActionLink("Реєстрація", "SignUp")
							</div>
						</form>
					</div>
				</div>
			</div>				
		</main>
	</div>
	
	<!--SCRIPTS-->
	<script src="../lib/jquery/dist/jquery.min.js"></script>
	<script src="../src/js/main.js"></script>
</body>
</html>

YourBookStore.PL/Views/Users/SignUp.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model YourBookStore.Domain.ViewModels.RegistrationViewModel
@{
    Layout = null;
 }
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="../css/style.css">
	<title>Document</title>
</head>

<body class="body_white">
	<div class="wrapper">
		<main class="main">
			<!--RENDER BODY-->
			<div class="row-container">
				<div class="left-container">
					<img src="../src/img/ui/library.svg" alt="" class="left-container__image">
				</div>
				<div class="right-container">
					<div class="right-container__content">
						<a asp-controller="Home" asp-action="Index" class="right-container__logo"><img src="../src/img/ui/logo.svg" alt=""></a>
						<form asp-area="" asp-controller="Users" asp-action="SignUp" method="post" class="sign-up-form">

							<div class="input-item">
								<span asp-validation-for="Email" class="error-message validation-error _regular-interface-font"></span>
								@Html.TextBoxFor(m => m.Email, new { placeholder = "Email*", type = "email", @class = "text-input input-large _input-large-description-font" })

							</div>
							<div class="input-item">
								<span asp-validation-for="LastName" class="error-message validation-error _regular-interface-font"></span>
								@Html.TextBoxFor(m => m.LastName, new { placeholder = "Прізвище*", type = "text", @class = "text-input input-large _input-large-description-font" })

							</div>
							<div class="input-item">
							<span asp-validation-for="FirstName" class="error-message validation-error _regular-interface-font"></span>
								@Html.TextBoxFor(m => m.FirstName, new { placeholder = "Ім'я*", type="text", @class = "text-input input-large _input-large-description-font" })
								
							</div>
							<div class="input-item">
								<span asp-validation-for="Phone" class="error-message validation-error _regular-interface-font"></span>
								@Html.TextBoxFor(m => m.Phone, new { placeholder = "Номер телефону*", type="tel", @class = "text-input input-large _input-large-description-font" })
							</div>
							<div class="input-item">
                            								<span asp-validation-for="City" class="error-message validation-error _regular-interface-font"></span>
                            								@Html.TextBoxFor(m => m.City, new { placeholder = "Ваше місто*", type = "text", @class = "text-input input-large _input-large-description-font" })
								                            </div>
							<div class="input-item">
								<span asp-validation-for="PostalCode" class="error-message validation-error _regular-interface-font"></span>
								@Html.TextBoxFor(m => m.PostalCode, new { placeholder = "Ваш поштовий індекс*", type = "text", @class = "text-input input-large _input-large-description-font" })
							</div>

							<div class="input-item">
							<span asp-validation-for="Password" class="error-message validation-error _regular-interface-font"></span>
								@Html.TextBoxFor(m => m.Password, new { placeholder = "Придумайте пароль*", type="password", @class = "text-input input-large _input-large-description-font" })
							</div>
							<div class="input-item">
							<span asp-validation-for="ConfirmPassword" class="error-message validation-error _regular-interface-font"></span>
								@Html.TextBoxFor(m => m.ConfirmPassword, new { placeholder = "Повторіть пароль*", type="password", @class = "text-input input-large _input-large-description-font" })
							</div>

							<input type="submit" class="button-large" value="Зареєструватися">
							<div class="sign-form__redirect _regular-interface-font">
								<span>У вас є аккаунт?</span>
							@Html.ActionLink("Увійти", "SignIn")
							</div>
						</form>
					</div>
				</div>
			</div>
			<!--RENDER BODY-->
		</main>
	</div>

	<!--SCRIPTS-->
	<script src="../lib/jquery/dist/jquery.min.js"></script>
	<script src="../src/js/main.js"></script>
</body>

</html>

YourBookStore.PL/Views/Users/UserProfile.cshtml

@using YourBookStore.Domain.DTOs
@model UserViewModel
@{
    Layout = "_LayoutWhite";
}

<div class="profile">
    <div class="profile__container">
        <div class="profile__header">
            <h1>Ваш профіль</h1>
        </div>
        <div class="profile__main">
            <div class="profile__image _ibg">
                <img src="../src/img/users/user_1.jpg" alt="">
            </div>
            <div class="profile__info">			
                <div class="profile__info-header">
                    <h3  class="profile__info-full-name">@Model.FirstName @Model.LastName</h3>
                    @Html.ActionLink("","EditProfile","Users",new {email= @Model.Email},new {@class ="_icon-edit"})
                    <a href="/SignOut" class="_icon-signout"></a>
                </div>					
									
                <h4 class="profile__info-role">Покупець</h4>
                <div class="profile__info-border"></div>									
                <span>Контактна інформація</span>
                <div class="profile__info-contact-information-container">
                    <div class="profile__info-box">
                        <ul>
                            <li>Телефон:</li>
                            <li>Email:</li>
                            <li>Місто:</li>
                            <li>Поштовий індекс:</li>
                        </ul>
                    </div>
                    <div class="profile__info-box green-font">
                        <ul>
                            <li>@Model.Phone</li>
                            <li>@Model.Email</li>
                            <li>@Model.City</li>
                            <li>@Model.PostalCode</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@if (ViewBag.Orders.Count != 0)
{
    <div class="order-history">
    <div class="order-history__container">
        <h3>Ваші замовлення</h3>
        <table class="order-history-table items-table">
            <tr class="order-history-table-header items-table__header">
                <td>Фото</td>
                <td>Книга</td>
                <td>Кількість</td>
                <td>Ціна</td>
                <td>Дата замовлення</td>
                <td>Статус замовлення</td>

            </tr>
            @foreach (OrderDTO order in @ViewBag.Orders)
            {
                @foreach (OrderDetailsDTO orderDetail in order.OrderDetails)
                {
                    
                    var imagePath = "src/img/books/"+orderDetail.Book.Code+".jpg";
                    <tr class="items-table__item">
                        <td class="order-history-thumbnail  _ibg">
                            <a href="" class="book-item__image">
                                <img src="@imagePath" alt="Книга">
                            </a>
                        </td>
                        <td class="order-history__info">
                            <a href="" class="book-item__title">
                                <h6 class="order-history__header">@orderDetail.Book.Title</h6>
                            </a>
                            <a href="" class="book-item__author _description-font">@orderDetail.Book.Author.FullName</a>
                        </td>
                        <td class="order-history-quantity">
                            @orderDetail.Quantity
                        </td>
                        <td class="order-history__price">
                            <h5>@orderDetail.Price.ToString().Remove(5) ₴</h5>
                        </td>
                        <td class="order-history__date">
                            @order.OrderDate
                        </td>
                        <td class="order-history__status">
                            <h5>@order.Status</h5>
                        </td>
                    </tr>
                }
            }
        </table>
    </div>
</div>
}
    


YourBookStore.PL/Views/Users/UserProfileEdit.cshtml
@model UserViewModel
@{
    Layout = "_LayoutWhite";
}
<div class="profile">
    <div class="profile__container">
        <div class="profile__header">
            <h1>Ваш профіль</h1>
        </div>
        @using (Html.BeginForm("EditProfile", "Users", FormMethod.Post))
        {
            <div class="profile__main">
            <div class="profile__image _ibg">
                <img src="../src/img/users/user_1.jpg" alt="">
            </div>
            <div class="profile__info">								
                <div class="profile__info-header">
                    <input type="text" asp-for=@Model.FirstName class="text-input input-large profile__info-header-input" placeholder=@Model.FirstName>
                    <span asp-validation-for=@Model.FirstName class="error-message validation-error _regular-interface-font"></span>
                    <input type="text" asp-for=@Model.LastName class="text-input input-large profile__info-header-input" placeholder=@Model.LastName>
                    <span asp-validation-for=@Model.LastName class="error-message validation-error _regular-interface-font"></span>
                    <button type="submit" class="_icon-check"></button>
                </div>	
                <h4 class="profile__info-role">Покупець</h4>
                <div class="profile__info-border"></div>									
                <span>Контактна інформація</span>
                <div class="profile__info-contact-information-container">
                    <div class="profile__info-box">
                        <ul>
                            <li>Телефон:</li>
                            <li>Email:</li>
                            <li>Поштовий індекс:</li>
                            <li>Місто:</li>
                        </ul>
                    </div>
                    <div class="profile__info-box green-font">
                        <ul>
                            <li><input class="text-input _input-description-font"
                                       type="text" asp-for=@Model.Phone  placeholder=@Model.Phone>
                                <span asp-validation-for=@Model.Phone class="error-message validation-error _regular-interface-font"></span></li>
                            <li>@Html.HiddenFor(x=>x.Email) <input class="text-input _input-description-font"
                                       type="email"asp-for=@Model.Email  value=@Model.Email disabled="disabled"></li>
                            <li><input class="text-input _input-description-font"
                                       type="text" asp-for=@Model.PostalCode  placeholder=@Model.PostalCode>
                                <span asp-validation-for=@Model.PostalCode  class="error-message validation-error _regular-interface-font"></span></li>
                            <li><input class="text-input _input-description-font"
                                       type="text" asp-for=@Model.City  placeholder=@Model.City>
                                <span asp-validation-for=@Model.City class="error-message validation-error _regular-interface-font"></span></li>
                        </ul>
                    </div>
                </div>
            </div>
            </div>
        }
    </div>
</div>